name: NASA Project CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Use Node.js version 21
      - uses: actions/setup-node@v3
        with: 
          node-version: "21"
      - run: npm install
      - run: npm run build --prefix client 
  deploy:
    needs: build